tunisia_mall_administration_homepage:
    path:     /hello/{name}
    defaults: { _controller: TunisiaMallAdministrationBundle:Default:index }
responsable:
    path:   /responsable
    defaults: { _controller: TunisiaMallAdministrationBundle:Default:responsable }
administrateur:
    path:   /administrateur
    defaults: { _controller: TunisiaMallAdministrationBundle:Default:administrateur }