<?php

namespace TunisiaMall\TunisiaMallBundle\Entity;

use Doctrine\ORM\EntityRepository;
use TunisiaMall\TunisiaMallBundle\Entity\CarteFidelite;



/**
 * CarteFidelite
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarteFideliteRepository extends EntityRepository
{
    public function modify($id,$points)
    {
   $query=$this->getEntityManager()->createQuery("Update TunisiaMallBundle:CarteFidelite c SET c.nbrePoint=:points where c.id=:id ");
      $query->setParameter('id',$id);
        $query->setParameter('points',$points);
         $query->execute();
    }
    public function supp($id)
    {
 $query=$this->getEntityManager()->createQuery("Delete from TunisiaMallBundle:CarteFidelite c where c.id=:id ");
        $query->setParameter('id',$id);
         $query->execute();

    }
}
