<?php

namespace TunisiaMall\TunisiaMallBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository {

    public function search($idenseigne) {

        $query = $this->createQueryBuilder('TunisiaMallBundle:Media')
                ->select('a.id,a.ref,a.nomProduit,a.description,a.idenseigne,a.nom_categorie,a.typeProduit,a.quantiteStock,a.prix,a.prixGros,m.path')
                ->distinct()
                ->from('TunisiaMallBundle:Produit', 'a')
                
                ->join('a.image', 'm')
                
              
               
                ->where('a.idenseigne=:idenseigne')
                ->setParameter('idenseigne', $idenseigne);
                
        return $query->getQuery()->getResult();
    }

    public function supp($id) {
        $query = $this->getEntityManager()->createQuery("Delete from TunisiaMallBundle:Produit a where a.id=:id ");
        $query->setParameter('id', $id);
        $query->execute();
    }

    public function modify($id, $nomProduit, $description, $typeProduit, $quantiteStock,$prix) {
        $query = $this->getEntityManager()
                ->createQuery("Update TunisiaMallBundle:Produit c SET c.nomProduit=:nomProduit,c.description=:description"
                . ",c.typeProduit=:typeProduit,c.quantiteStock=:quantiteStock,c.prix=:prix"
                               . " where c.id=:id ");
        $query->setParameter('id', $id);
        $query->setParameter('nomProduit', $nomProduit);
        $query->setParameter('description', $description);
        $query->setParameter('typeProduit', $typeProduit);
        $query->setParameter('quantiteStock', $quantiteStock);
       $query->setParameter('prix', $prix);

        $query->execute();
    }
     public function search_nom_article($nomProduit) {

        $query = $this->createQueryBuilder('TunisiaMallBundle:Media')
                ->select('a.id,a.ref,a.nomProduit,a.description,a.idenseigne,a.nom_categorie,a.typeProduit,a.quantiteStock,a.prix,a.prixGros,m.path')
                ->distinct()
                ->from('TunisiaMallBundle:Produit', 'a')
                ->join('a.image', 'm')
                ->where('a.nomProduit LIKE :nomProduit')
                  ->setParameter('nomProduit','%'.$nomProduit.'%');

        return $query->getQuery()->getResult();
    }

}
