<?php

namespace TunisiaMall\TunisiaMallBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * visitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visitorRepository extends EntityRepository
{
}
